package UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import UI.*;
import clientescriptori.Connection;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import objectes.Llibre;

/**
 *
 * @author Gonzalo
 */
public class AdministraLlibre extends javax.swing.JPanel {

    /**
     * Creates new form BuscaLlibre
     */
    Connection connexio;
    LoginScreen loginScreen;
    
    public AdministraLlibre() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNom = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelEditorial = new javax.swing.JLabel();
        jLabelIdioma = new javax.swing.JLabel();
        jLabelAny = new javax.swing.JLabel();
        jLabelNota = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldEditorial = new javax.swing.JTextField();
        jTextFieldIdioma = new javax.swing.JTextField();
        jTextFieldAny = new javax.swing.JTextField();
        jTextFieldNota = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEsborrar = new javax.swing.JButton();
        jTextFieldIlustrador = new javax.swing.JTextField();
        jLabelIlustrador = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabelNom.setText("Nom:");

        jLabelAutor.setText("Autor:");

        jLabelId.setText("ID:");

        jLabelEditorial.setText("Editorial:");

        jLabelIdioma.setText("Idioma:");

        jLabelAny.setText("Any:");

        jLabelNota.setText("Nota:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonEsborrar.setText("Esborrar");
        jButtonEsborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEsborrarActionPerformed(evt);
            }
        });

        jLabelIlustrador.setText("Ilustrador/a:");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel1.setText("Administrar llibres:");

        jLabel2.setText("ISBN:");

        jButtonCrear.setBackground(new java.awt.Color(102, 255, 0));
        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelIlustrador)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldIlustrador))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEditorial)
                                        .addComponent(jLabelAny)
                                        .addComponent(jLabelNota)
                                        .addComponent(jLabelIdioma))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldIdioma)
                                        .addComponent(jTextFieldNota)
                                        .addComponent(jTextFieldAny)
                                        .addComponent(jTextFieldEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabelId, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabelAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNom))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNom)
                                    .addComponent(jTextFieldAutor)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCrear)
                                    .addComponent(jButtonEsborrar))))
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutor)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEsborrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEditorial)
                            .addComponent(jTextFieldEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIdioma)
                            .addComponent(jTextFieldIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButtonCrear)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAny)
                    .addComponent(jTextFieldAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNota)
                    .addComponent(jTextFieldNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIlustrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIlustrador))
                .addContainerGap(233, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        List<Llibre> listaLlibres = connexio.buscaLlibres(creaArrayStringLlibre());
        System.out.println("lista libros cantidad: " + listaLlibres.size());
        loginScreen.showBookListAdmin(listaLlibres);
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEsborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsborrarActionPerformed
        jTextFieldNom.setText("");
        jTextFieldAutor.setText("");
        jTextFieldId.setText("");
        jTextFieldEditorial.setText("");
        jTextFieldAny.setText("");
        jTextFieldIdioma.setText("");
        jTextFieldNota.setText("");
        jTextFieldIlustrador.setText("");
    }//GEN-LAST:event_jButtonEsborrarActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        try {
            connexio.creaLlibre(creaArrayStringLlibre());
        } catch (IOException ex) {
            Logger.getLogger(AdministraLlibre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEsborrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAny;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelEditorial;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdioma;
    private javax.swing.JLabel jLabelIlustrador;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNota;
    private javax.swing.JTextField jTextFieldAny;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldEditorial;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdioma;
    private javax.swing.JTextField jTextFieldIlustrador;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldNota;
    // End of variables declaration//GEN-END:variables

    public void setConnexio(Connection con){
        this.connexio = con;
    }
    
    public void setLoginScreen(LoginScreen login){
        this.loginScreen = login;
    }
    
    private String[] creaArrayStringLlibre(){
        String nom = "";
        if(jTextFieldNom.getText() != null) nom=jTextFieldNom.getText();
        String autor = "";
        if(jTextFieldAutor.getText() != null) autor=jTextFieldAutor.getText();
        String isbn = "";
        if(jTextFieldISBN.getText()!= null) isbn = jTextFieldISBN.getText();
        String editorial = "";
        if(jTextFieldEditorial.getText() != null) editorial=jTextFieldEditorial.getText();
        String idioma = "";
        if(jTextFieldIdioma.getText() != null) idioma=jTextFieldIdioma.getText();
        String any = "";
        if(jTextFieldAny.getText() != null) any=jTextFieldAny.getText();
        String nota = "";
        if(jTextFieldNota != null) nota=jTextFieldNota.getText();
        String ilustrador = "";
        if(jTextFieldIlustrador.getText() != null) ilustrador=jTextFieldIlustrador.getText();

        String[] llibre = {nom, autor, isbn, editorial, any, "", "", ilustrador, null, idioma, null, nota, "", ""};
            
        return llibre;
    }
}
