/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import objectes.Comentari;
import objectes.Llibre;
import clientescriptori.Connection;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;

/**
 *
 * @author Gonzalo
 */
public class ComentarisLlibre extends javax.swing.JPanel {

    private Llibre llibre;
    private InfoLlibre infoLlibre;
    private List<Comentari> listaComentaris;
    private Connection connection;

    /**
     * Creates new form ComentarisLlibre
     */
    public ComentarisLlibre() {
        initComponents();
    }

    public ComentarisLlibre(Llibre llibre, InfoLlibre infoLlibre) throws ClassNotFoundException {
        initComponents();
        this.llibre = llibre;
        this.infoLlibre = infoLlibre;
        jLabelTitol.setText("Comentaris sobre: " + llibre.getTitol());

        carregaComentaris();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitol = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPanePrincipal = new javax.swing.JScrollPane();
        jPanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNouComentari = new javax.swing.JTextArea();
        jLabelEscriureComentari = new javax.swing.JLabel();
        jButtonEnviarComentari = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabelTitol.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitol.setText("Comentaris sobre: ?");

        jButton1.setText("Tornar enrere");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelPrincipal.setBackground(new java.awt.Color(0, 204, 204));
        jPanelPrincipal.setLayout(new javax.swing.BoxLayout(jPanelPrincipal, javax.swing.BoxLayout.Y_AXIS));
        jScrollPanePrincipal.setViewportView(jPanelPrincipal);

        jTextAreaNouComentari.setColumns(20);
        jTextAreaNouComentari.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNouComentari);

        jLabelEscriureComentari.setText("Escriure comentari:");

        jButtonEnviarComentari.setText("Enviar comentari");
        jButtonEnviarComentari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarComentariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitol)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelEscriureComentari)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(jButtonEnviarComentari)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEscriureComentari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonEnviarComentari))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            infoLlibre.amagaComentaris();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ComentarisLlibre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEnviarComentariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarComentariActionPerformed
        String comentariString = jTextAreaNouComentari.getText();
        boolean enviaComentari = connection.enviaComentari(comentariString, llibre.getId());

        if (enviaComentari) {
            try {
                jTextAreaNouComentari.setText("");
                JOptionPane.showMessageDialog(this, "Comentari enviat correctament.",
                    "Comentari enviat", JOptionPane.INFORMATION_MESSAGE);
                carregaComentaris();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No s'ha pogut guardar el comentari.\n"
                    + "Torni a provar passat un moment o contacti amb l'administrador del sistema.  ",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonEnviarComentariActionPerformed

    private void carregaComentaris() throws ClassNotFoundException {

        jPanelPrincipal.removeAll();
        listaComentaris = Connection.buscaComentaris(llibre.getId());

        System.out.println("comentaris trobats: " + listaComentaris.size());

        for (Comentari comentari : listaComentaris) {
            JPanel panelComentario = new JPanel(new FlowLayout(FlowLayout.LEFT));
            JLabel lblUsuari = new JLabel("Usuari: " + comentari.getIdUsuari() + " - ");
            JTextArea txtComentari = new JTextArea(comentari.getComentari());
            
            txtComentari.setLineWrap(true);
            txtComentari.setWrapStyleWord(true);
            txtComentari.setEditable(false);
            
            panelComentario.add(lblUsuari);
            panelComentario.add(txtComentari);
            panelComentario.revalidate();
            panelComentario.repaint();
            
            jPanelPrincipal.add(panelComentario);
            
            JSeparator separator = new JSeparator();
            jPanelPrincipal.add(separator);
            
            jPanelPrincipal.revalidate();
            jPanelPrincipal.repaint();
        }
    }

    public void setConnection(Connection con){
        this.connection = con;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEnviarComentari;
    private javax.swing.JLabel jLabelEscriureComentari;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanePrincipal;
    private javax.swing.JTextArea jTextAreaNouComentari;
    // End of variables declaration//GEN-END:variables
}
