/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import static UI.PerfilUsuari.convertirDataString;
import clientescriptori.Connection;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import objectes.Usuari;
import objectes.XifradorContrasenya;
import utils.Utils;

/**
 *
 * @author Gonzalo
 */
public class InfoUsuari extends javax.swing.JFrame {

    private Usuari usuari;
    private Connection connexio;
    private ImageIcon fotoPerfilIcon;
    private Image fotoPerfil;
    private XifradorContrasenya xC;

    /**
     * Creates new form InfoUsuari
     */
    public InfoUsuari() {
        initComponents();
    }

    public InfoUsuari(Usuari usuari) {
        this.usuari = usuari;
        initComponents();
        jTextFieldId.setText(usuari.getUser());
        jTextFieldNomUsuari.setText(usuari.getNom());
        jTextFielCognoms.setText(usuari.getPrimerCognom() + " " + usuari.getSegonCognom());
        if (usuari.getDataNaixement() != null) {
            jTextFielIdDataNaixement.setText(usuari.getDataNaixement().toString());
        }
        jTextFielIdEmail.setText(usuari.getEmail());
        try {
            setUsuari(usuari);
        } catch (Exception e) {
        }
        xC = new XifradorContrasenya();
    }

    public void setUsuari(Usuari user) throws IOException {

        System.out.println("cargando imagen del usuario...");
        try {

            ByteArrayInputStream inputStream = new ByteArrayInputStream(usuari.getImageData());

            // Crear objecte Image a partir del InputStream
            Image imagen = ImageIO.read(inputStream);
            ImageIcon imageIcon = new ImageIcon(imagen);
            setImageIcon(escalarImagen(jPanelImagen, imageIcon));

        } catch (Exception e) {
            System.out.println("error: " + e);
            System.out.println(usuari.getImageData());
        }
//        if (usuari.getImageData() != null) {
//            try {
//                setImageIcon(Utils.convertirBytesAImagen(usuari.getImageData()));
//            } catch (Exception e) {
//                System.out.println("error: " + e + " imposible cargar foto perfil");
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomUsuari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFielCognoms = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFielIdDataNaixement = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFielIdEmail = new javax.swing.JTextField();
        jButtonDesferCanvis = new javax.swing.JButton();
        jButtonGuardarCanvis = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonActualitzaContrassenya = new javax.swing.JButton();
        jPanelImagen = new javax.swing.JPanel();
        jLabelFotoPerfil = new javax.swing.JLabel();
        jButtonEditarImatge = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setMinimumSize(getPreferredSize());
        jPanel1.setPreferredSize(getPreferredSize());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID d'usuari:");

        jLabel5.setText("Nom:");

        jTextFieldId.setEditable(false);

        jTextFielCognoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielCognomsActionPerformed(evt);
            }
        });

        jLabel6.setText("Cognoms:");

        jLabel7.setText("Data naixement:");

        jTextFielIdDataNaixement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdDataNaixementActionPerformed(evt);
            }
        });

        jLabel8.setText("Email:");

        jTextFielIdEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdEmailActionPerformed(evt);
            }
        });

        jButtonDesferCanvis.setText("Desfer canvis");
        jButtonDesferCanvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesferCanvisActionPerformed(evt);
            }
        });

        jButtonGuardarCanvis.setText("Guardar canvis");
        jButtonGuardarCanvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCanvisActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("Perfil d'usuari:");

        jButtonActualitzaContrassenya.setText("Canviar contrassenya");
        jButtonActualitzaContrassenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualitzaContrassenyaActionPerformed(evt);
            }
        });

        jPanelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_user.jpg"))); // NOI18N
        jLabelFotoPerfil.setToolTipText("");
        jPanelImagen.add(jLabelFotoPerfil);

        jButtonEditarImatge.setText("Editar imatge");
        jButtonEditarImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarImatgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel1)
                                    .addGap(11, 11, 11)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(jButtonActualitzaContrassenya, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)
                            .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addComponent(jButtonEditarImatge))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel5)
                            .addGap(10, 10, 10)
                            .addComponent(jTextFieldNomUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel6)
                            .addGap(5, 5, 5)
                            .addComponent(jTextFielCognoms, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel7)
                            .addGap(4, 4, 4)
                            .addComponent(jTextFielIdDataNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8)
                            .addGap(8, 8, 8)
                            .addComponent(jTextFielIdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jButtonDesferCanvis)
                            .addGap(11, 11, 11)
                            .addComponent(jButtonGuardarCanvis)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addComponent(jButtonActualitzaContrassenya))
                        .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addComponent(jButtonEditarImatge)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jTextFieldNomUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jTextFielCognoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jTextFielIdDataNaixement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jTextFielIdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonDesferCanvis)
                        .addComponent(jButtonGuardarCanvis))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielCognomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielCognomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielCognomsActionPerformed

    private void jTextFielIdDataNaixementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdDataNaixementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdDataNaixementActionPerformed

    private void jTextFielIdEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdEmailActionPerformed

    private void jButtonDesferCanvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesferCanvisActionPerformed
        jTextFieldNomUsuari.setText(usuari.getNom());
        jTextFielCognoms.setText(usuari.getPrimerCognom() + " " + usuari.getSegonCognom());
        if (usuari.getDataNaixement() != null) {
            jTextFielIdDataNaixement.setText(usuari.getDataNaixement().toString());
        } else {
            jTextFielIdDataNaixement.setText(null); //falta implementar calendari per seleccionar data
        }
        jTextFielIdEmail.setText(usuari.getEmail());
    }//GEN-LAST:event_jButtonDesferCanvisActionPerformed

    private void jButtonGuardarCanvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCanvisActionPerformed

        usuari.setNom(jTextFieldNomUsuari.getText());
        String cognoms = jTextFielCognoms.getText();
        String[] arrayCognoms = cognoms.split(" ");

        if (arrayCognoms.length > 0) {
            usuari.setPrimerCognom(arrayCognoms[0]);
        }
        if (arrayCognoms.length > 1) {
            usuari.setSegonCognom(arrayCognoms[1]);
        }
        try {
            usuari.setDataNaixement(convertirDataString(jTextFielIdDataNaixement.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
        }
        usuari.setEmail(jTextFielIdEmail.getText());

        //usuari.setPass(xC.Desxifradorbyte(usuari.getPassX()));
        Connection.modificarUsuariSenseXifrar(usuari);
        JOptionPane.showMessageDialog(this, "Informació actualitzada amb éxit");
    }//GEN-LAST:event_jButtonGuardarCanvisActionPerformed

    private void jButtonActualitzaContrassenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualitzaContrassenyaActionPerformed

        CanviaPassTercer canviaPassTercer = new CanviaPassTercer(usuari);
        canviaPassTercer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        canviaPassTercer.setVisible(true);

    }//GEN-LAST:event_jButtonActualitzaContrassenyaActionPerformed

    private void jButtonEditarImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarImatgeActionPerformed
        //obrim el menu per buscar arxius:
        JFileChooser selectorArxius = new JFileChooser();
        selectorArxius.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen",
                "jpg", "jpeg", "png", "gif");
        selectorArxius.addChoosableFileFilter(filtro);
        selectorArxius.setFileFilter(filtro);

        int result = selectorArxius.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File imatge = selectorArxius.getSelectedFile();
            fotoPerfilIcon = new ImageIcon(imatge.getPath());
            try {
                fotoPerfil = ImageIO.read(imatge);
            } catch (IOException ex) {
                Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
            }

            jLabelFotoPerfil.setIcon(escalarImagen(jPanelImagen, fotoPerfilIcon));
            BufferedImage bi = new BufferedImage(fotoPerfilIcon.getIconWidth(), fotoPerfilIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
            fotoPerfilIcon.paintIcon(null, bi.getGraphics(), 0, 0);
            try {
                byte[] fotoPerfilBytes = Utils.convertirImagenABytes(bi);
                usuari.setImageData(fotoPerfilBytes);
                Connection.modificarUsuariSenseXifrar(usuari);
            } catch (IOException ex) {
                Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonEditarImatgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoUsuari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoUsuari().setVisible(true);
            }
        });
    }

    public ImageIcon escalarImagen(JPanel panel, ImageIcon imageIcon) {
        //Obtenim el tamany del panell
        int panelWidth = panel.getWidth();
        int panelHeight = panel.getHeight();

        //Obtenim el tamany de l'imageIcon
        int imageWidth = imageIcon.getIconWidth();
        int imageHeight = imageIcon.getIconHeight();

        //calculem l'escala necessària per que l'imatge s'ajusti
        double escala = Math.min((double) panelWidth / imageWidth, (double) panelHeight / imageHeight);
        Image imatgeEscalada = imageIcon.getImage().getScaledInstance((int) (imageWidth * escala),
                (int) (imageHeight * escala), Image.SCALE_SMOOTH);

        ImageIcon imageIconEscalat = new ImageIcon(imatgeEscalada);

        return imageIconEscalat;
    }

    public void setImageIcon(ImageIcon imageIcon) {

        this.fotoPerfilIcon = imageIcon;
        jLabelFotoPerfil.setIcon(escalarImagen(jPanelImagen, fotoPerfilIcon));
        BufferedImage bi = new BufferedImage(fotoPerfilIcon.getIconWidth(), fotoPerfilIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
        fotoPerfilIcon.paintIcon(null, bi.getGraphics(), 0, 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualitzaContrassenya;
    private javax.swing.JButton jButtonDesferCanvis;
    private javax.swing.JButton jButtonEditarImatge;
    private javax.swing.JButton jButtonGuardarCanvis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFotoPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JTextField jTextFielCognoms;
    private javax.swing.JTextField jTextFielIdDataNaixement;
    private javax.swing.JTextField jTextFielIdEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNomUsuari;
    // End of variables declaration//GEN-END:variables
}
