/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import objectes.Llibre;
import clientescriptori.Connection;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import objectes.Comentari;

/**
 *
 * @author Gonzalo
 */
public class InfoLlibre extends javax.swing.JFrame {

    private Llibre llibre;
    private List<Comentari> listaComentaris;
    private Connection connection;

    /**
     * Creates new form InfoLlibre
     */
    public InfoLlibre() {
        initComponents();
    }

    public InfoLlibre(Llibre llibre) {
        initComponents();
        this.llibre = llibre;

        jTextFieldTitol.setText(llibre.getTitol());
        jTextFieldAutor.setText(llibre.getAutor());
        jTextFieldId.setText(String.valueOf(llibre.getId()));
        jTextFieldISBN.setText(llibre.getIsbn());
        jTextFieldEditorial.setText(llibre.getEditorial());
        jTextFieldAny.setText(String.valueOf(llibre.getAnyPublicacio()));
        jTextFieldIlustrador.setText(llibre.getIllustrador());
        jTextFieldIdioma.setText(llibre.getIdioma());
        jTextFieldPagines.setText(String.valueOf(llibre.getPagines()));
        jTextFieldNota.setText(llibre.getNota());
        jTextFieldTitolOriginal.setText(llibre.getTitolOriginal());
        jTextFieldTraductor.setText(llibre.getTraductor());
        jTextAreaDescripcio.setText(llibre.getDescripcio());

        try {
            listaComentaris = Connection.buscaComentaris(llibre.getId());
            jButtonComentaris.setText("Comentaris (" + listaComentaris.size() + ")");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InfoLlibre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelComentaris = new javax.swing.JPanel();
        jPanelInformacioLlibre = new javax.swing.JPanel();
        jLabelTituloVentana = new javax.swing.JLabel();
        jLabelTitol = new javax.swing.JLabel();
        jTextFieldTitol = new javax.swing.JTextField();
        jLabelDescripcio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcio = new javax.swing.JTextArea();
        jLabelIlustrador = new javax.swing.JLabel();
        jTextFieldIlustrador = new javax.swing.JTextField();
        jLabelPagines = new javax.swing.JLabel();
        jTextFieldPagines = new javax.swing.JTextField();
        jLabelIdioma = new javax.swing.JLabel();
        jTextFieldIdioma = new javax.swing.JTextField();
        jLabelNota = new javax.swing.JLabel();
        jTextFieldNota = new javax.swing.JTextField();
        jLabelTitolOriginal = new javax.swing.JLabel();
        jTextFieldTitolOriginal = new javax.swing.JTextField();
        jLabelTraductor = new javax.swing.JLabel();
        jTextFieldTraductor = new javax.swing.JTextField();
        jButtonVeurePortada = new javax.swing.JButton();
        jButtonTornarEnrere = new javax.swing.JButton();
        jButtonReservar = new javax.swing.JButton();
        jButtonComentaris = new javax.swing.JButton();
        jLabelAutor = new javax.swing.JLabel();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEditorial = new javax.swing.JTextField();
        jLabelAny = new javax.swing.JLabel();
        jTextFieldAny = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanelComentaris.setBackground(new java.awt.Color(153, 51, 255));
        jPanelComentaris.setLayout(new java.awt.BorderLayout());

        jPanelInformacioLlibre.setBackground(new java.awt.Color(153, 204, 255));
        jPanelInformacioLlibre.setLayout(new java.awt.GridBagLayout());

        jLabelTituloVentana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTituloVentana.setText("Informació del llibre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 29, 0, 0);
        jPanelInformacioLlibre.add(jLabelTituloVentana, gridBagConstraints);

        jLabelTitol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitol.setText("Títol:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelTitol, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldTitol, gridBagConstraints);

        jLabelDescripcio.setText("Descripció:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelDescripcio, gridBagConstraints);

        jTextAreaDescripcio.setColumns(20);
        jTextAreaDescripcio.setLineWrap(true);
        jTextAreaDescripcio.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescripcio);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 201;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanelInformacioLlibre.add(jScrollPane1, gridBagConstraints);

        jLabelIlustrador.setText("Ilustrador:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelIlustrador, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldIlustrador, gridBagConstraints);

        jLabelPagines.setText("Pàgines:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelPagines, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldPagines, gridBagConstraints);

        jLabelIdioma.setText("Idioma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelIdioma, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 30;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldIdioma, gridBagConstraints);

        jLabelNota.setText("Nota:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelNota, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 41;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanelInformacioLlibre.add(jTextFieldNota, gridBagConstraints);

        jLabelTitolOriginal.setText("Títol original:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelTitolOriginal, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 46;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 78;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanelInformacioLlibre.add(jTextFieldTitolOriginal, gridBagConstraints);

        jLabelTraductor.setText("Traductor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelTraductor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 43;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 6);
        jPanelInformacioLlibre.add(jTextFieldTraductor, gridBagConstraints);

        jButtonVeurePortada.setText("Veure portada");
        jButtonVeurePortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeurePortadaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanelInformacioLlibre.add(jButtonVeurePortada, gridBagConstraints);

        jButtonTornarEnrere.setText("Tornar enrere");
        jButtonTornarEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornarEnrereActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 8, 14, 0);
        jPanelInformacioLlibre.add(jButtonTornarEnrere, gridBagConstraints);

        jButtonReservar.setText("Reservar");
        jButtonReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 53;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 14, 6);
        jPanelInformacioLlibre.add(jButtonReservar, gridBagConstraints);

        jButtonComentaris.setText("Comentaris (?)");
        jButtonComentaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComentarisActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 53;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        jPanelInformacioLlibre.add(jButtonComentaris, gridBagConstraints);

        jLabelAutor.setText("Autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelAutor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldAutor, gridBagConstraints);

        jLabelId.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldId, gridBagConstraints);

        jLabelISBN.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelISBN, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 159;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldISBN, gridBagConstraints);

        jLabel1.setText("Editorial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 30;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 147;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldEditorial, gridBagConstraints);

        jLabelAny.setText("Any:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 6, 0, 0);
        jPanelInformacioLlibre.add(jLabelAny, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
        jPanelInformacioLlibre.add(jTextFieldAny, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInformacioLlibre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelComentaris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInformacioLlibre, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelComentaris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVeurePortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeurePortadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeurePortadaActionPerformed

    private void jButtonTornarEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTornarEnrereActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonTornarEnrereActionPerformed

    private void jButtonComentarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComentarisActionPerformed

        jPanelInformacioLlibre.setVisible(false);

        try {
            ComentarisLlibre comentarisLlibre;
            if (llibre != null) {
                comentarisLlibre = new ComentarisLlibre(llibre, this);
            } else {
                comentarisLlibre = new ComentarisLlibre();
            }
            comentarisLlibre.setConnection(connection);
            jPanelComentaris.setVisible(true);
            jPanelComentaris.add(comentarisLlibre, BorderLayout.CENTER);
            System.out.println("comentarioslibro" + comentarisLlibre.isShowing());

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonComentarisActionPerformed

    private void jButtonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservarActionPerformed
        try {
            Connection.crearReserva(llibre.getId());
            String missatge = "S'ha efectuat la reserva del llibre " + llibre.getTitol() + ".";
            JOptionPane.showMessageDialog(this, missatge,
                    "Reserva efectuada", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(InfoLlibre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonReservarActionPerformed

    public void amagaComentaris() throws ClassNotFoundException {
        listaComentaris = Connection.buscaComentaris(llibre.getId());
        jButtonComentaris.setText("Comentaris (" + listaComentaris.size() + ")");
        jPanelComentaris.setVisible(false);
        jPanelInformacioLlibre.setVisible(true);
        jPanelInformacioLlibre.revalidate();
        jPanelInformacioLlibre.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoLlibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoLlibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoLlibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoLlibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoLlibre().setVisible(true);
            }
        });
    }

    public void setConnection(Connection connection) {
        this.connection = connection;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComentaris;
    private javax.swing.JButton jButtonReservar;
    private javax.swing.JButton jButtonTornarEnrere;
    private javax.swing.JButton jButtonVeurePortada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAny;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelDescripcio;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelIdioma;
    private javax.swing.JLabel jLabelIlustrador;
    private javax.swing.JLabel jLabelNota;
    private javax.swing.JLabel jLabelPagines;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JLabel jLabelTitolOriginal;
    private javax.swing.JLabel jLabelTituloVentana;
    private javax.swing.JLabel jLabelTraductor;
    private javax.swing.JPanel jPanelComentaris;
    private javax.swing.JPanel jPanelInformacioLlibre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescripcio;
    private javax.swing.JTextField jTextFieldAny;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldEditorial;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldIdioma;
    private javax.swing.JTextField jTextFieldIlustrador;
    private javax.swing.JTextField jTextFieldNota;
    private javax.swing.JTextField jTextFieldPagines;
    private javax.swing.JTextField jTextFieldTitol;
    private javax.swing.JTextField jTextFieldTitolOriginal;
    private javax.swing.JTextField jTextFieldTraductor;
    // End of variables declaration//GEN-END:variables
}
