/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import objectes.Usuari;

/**
 *
 * @author Gonzalo
 */
public class LlistaUsuaris extends javax.swing.JPanel {

    /**
     * Creates new form LlistaUsuaris
     */
    ArrayList<Usuari> userList;
    DefaultTableModel dtmUsuaris = new DefaultTableModel();
    LoginScreen loginScreen;

    public LlistaUsuaris(ArrayList<Usuari> userList, LoginScreen loginScreen) {
        initComponents();
        this.loginScreen = loginScreen;
        this.userList = userList;
        

        setModelo();
        setDatos();
    }

    //Establim el format de la taula
    private void setModelo() {
        String[] cabecera = {"User", "Rol", "Data naixement", "Nom", "Primer cognom", "Segon cognom", "Email"};
        dtmUsuaris.setColumnIdentifiers(cabecera);
        
        jTable1.setModel(dtmUsuaris);
        
    }

    //Métode per afegir la llista d'usuaris trobats a la taula.
    private void setDatos() {
        Object[] datos = new Object[dtmUsuaris.getColumnCount()];
        for (Usuari user : userList) {
            datos[0] = user.getId();
            datos[1] = user.getRol();
            datos[2] = user.getData().toString();
            datos[3] = user.getNom();
            datos[4] = user.getPrimerCognom();
            datos[5] = user.getSegonCognom();
            datos[6] = user.getEmail();

            //afegim la fila al default table model
            dtmUsuaris.addRow(datos);
        }
        //afegim el default table model a la taula:
        jTable1.setModel(dtmUsuaris);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonTornarEnrere = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Usuaris trobats:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        jButtonTornarEnrere.setText("Tornar enrere");
        jButtonTornarEnrere.setMaximumSize(new java.awt.Dimension(500, 22));
        jButtonTornarEnrere.setPreferredSize(new java.awt.Dimension(300, 22));
        jButtonTornarEnrere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTornarEnrereActionPerformed(evt);
            }
        });
        add(jButtonTornarEnrere, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 400, 240));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Eliminar usuari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 290, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTornarEnrereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTornarEnrereActionPerformed
        loginScreen.showSearchUser();
    }//GEN-LAST:event_jButtonTornarEnrereActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row = jTable1.getSelectedRow();
        
        
        int value = (int) jTable1.getValueAt(row, 0);
        try {
            System.out.println("esborrant: " + value);
            loginScreen.getConnexio().esborrarUsuari(Integer.toString(value));
        } catch (IOException ex) {
            Logger.getLogger(LlistaUsuaris.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTornarEnrere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private Object[] getFilaTabla(Usuari user) {
        Object[] usuariArray = {user.getId(), user.getRol(), user.getDataNaixement(), user.getNom(), user.getPrimerCognom(), user.getSegonCognom(), user.getEmail()};

        return usuariArray;
    }
}
