/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import clientescriptori.Connection;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.Box;
import javax.swing.JOptionPane;

/**
 *
 * @author Gonzalo
 */
public class LoginScreen extends javax.swing.JFrame {

    public static String usuari, codi, rol;
    private String contrassenya;
    private Connection connexio;
    PerfilUsuari perfilUsuariPanel;
    
    /**
     * Creates new form loginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanelLateral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2ContenedorBotones = new javax.swing.JPanel();
        jPanelUsuario1 = new javax.swing.JPanel();
        jPanelUsuario = new javax.swing.JPanel();
        jLabelBenvinguda = new javax.swing.JLabel();
        jButtonPerfil = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelBibliotecari1 = new javax.swing.JPanel();
        jPanelBibliotecari = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelAdmin1 = new javax.swing.JPanel();
        jPanelAdmin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelMenus = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUsuari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ButtonIniciarSessio = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTitolRol = new javax.swing.JLabel();
        jLabelTitolMenu = new javax.swing.JLabel();
        jPanelContenedorMenus = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de gestió de prèstecs BiblioEdu");
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(589, 387));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanelLateral.setBackground(new java.awt.Color(51, 204, 255));
        jPanelLateral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelLateral.setForeground(new java.awt.Color(153, 204, 255));
        jPanelLateral.setMinimumSize(new java.awt.Dimension(250, 400));
        jPanelLateral.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanelLateral.setLayout(new javax.swing.BoxLayout(jPanelLateral, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BiblioEdu");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setAlignmentY(1.0F);
        jPanelLateral.add(jLabel1);

        jPanel2ContenedorBotones.setVisible(false);
        jPanel2ContenedorBotones.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2ContenedorBotones.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel2ContenedorBotones.setLayout(new javax.swing.BoxLayout(jPanel2ContenedorBotones, javax.swing.BoxLayout.Y_AXIS));

        jPanelUsuario1.setBackground(new java.awt.Color(51, 204, 255));
        jPanelUsuario1.setMaximumSize(new java.awt.Dimension(1000, 1350));
        jPanelUsuario1.setLayout(new javax.swing.BoxLayout(jPanelUsuario1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelUsuario.setVisible(false);
        jPanelUsuario.setBackground(new java.awt.Color(51, 204, 255));
        jPanelUsuario.setMaximumSize(new java.awt.Dimension(1000, 1350));
        jPanelUsuario.setLayout(new java.awt.GridLayout(4, 1, 4, 3));

        jLabelBenvinguda.setText("  Benvingut/da, ");
        jPanelUsuario.add(jLabelBenvinguda);

        jButtonPerfil.setText("El meu perfil");
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });
        jPanelUsuario.add(jButtonPerfil);

        jButton2.setText("Les meves reserves");
        jPanelUsuario.add(jButton2);

        jButton3.setText("Buscar");
        jPanelUsuario.add(jButton3);

        jPanelUsuario1.add(jPanelUsuario);

        jPanel2ContenedorBotones.add(jPanelUsuario1);

        jPanelBibliotecari1.setBackground(new java.awt.Color(51, 204, 255));
        jPanelBibliotecari1.setMaximumSize(new java.awt.Dimension(32767, 1500));
        jPanelBibliotecari1.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelBibliotecari1.setLayout(new javax.swing.BoxLayout(jPanelBibliotecari1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelBibliotecari.setBackground(new java.awt.Color(51, 204, 255));
        jPanelBibliotecari.setMaximumSize(new java.awt.Dimension(32767, 1500));
        jPanelBibliotecari.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanelBibliotecari.setLayout(new java.awt.GridLayout(3, 0));

        jLabel7.setText("  Bibliotecari/a:");
        jPanelBibliotecari.setVisible(false);
        jPanelBibliotecari.add(jLabel7);

        jButton6.setText("Administrar reserves");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelBibliotecari.add(jButton6);

        jButton4.setText("Administrar llibres");
        jButton4.setMargin(new java.awt.Insets(5, 14, 5, 14));
        jButton4.setMaximumSize(new java.awt.Dimension(72, 22));
        jButton4.setMinimumSize(new java.awt.Dimension(72, 22));
        jButton4.setPreferredSize(new java.awt.Dimension(72, 22));
        jPanelBibliotecari.add(jButton4);

        jPanelBibliotecari1.add(jPanelBibliotecari);

        jPanel2ContenedorBotones.add(jPanelBibliotecari1);

        jPanelAdmin.setVisible(false);
        jPanelAdmin1.setBackground(new java.awt.Color(51, 204, 255));
        jPanelAdmin1.setMaximumSize(new java.awt.Dimension(1000, 400));
        jPanelAdmin1.setLayout(new javax.swing.BoxLayout(jPanelAdmin1, javax.swing.BoxLayout.LINE_AXIS));

        jPanelAdmin.setVisible(false);
        jPanelAdmin.setBackground(new java.awt.Color(51, 204, 255));
        jPanelAdmin.setMaximumSize(new java.awt.Dimension(1000, 400));
        jPanelAdmin.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabel8.setText("  Administrador:");
        jPanelAdmin.add(jLabel8);

        jButton5.setText("Administrar usuaris");
        jPanelAdmin.add(jButton5);

        jPanelAdmin1.add(jPanelAdmin);

        jPanel2ContenedorBotones.add(jPanelAdmin1);

        jPanelLateral.add(jPanel2ContenedorBotones);

        jButtonLogout.setBackground(new java.awt.Color(255, 51, 51));
        jButtonLogout.setVisible(false);
        jButtonLogout.setText("Tancar sessió");
        jButtonLogout.setAlignmentX(0.5F);
        jButtonLogout.setAlignmentY(0.0F);
        jButtonLogout.setMaximumSize(new java.awt.Dimension(140, 32));
        jButtonLogout.setMinimumSize(new java.awt.Dimension(99, 32));
        jButtonLogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanelLateral.add(jButtonLogout);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(jPanelLateral, gridBagConstraints);

        jPanelMenus.setLayout(new java.awt.CardLayout());

        jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLogin.setMinimumSize(new java.awt.Dimension(410, 389));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(410, 389));
        java.awt.GridBagLayout jPanelLoginLayout = new java.awt.GridBagLayout();
        jPanelLoginLayout.columnWidths = new int[] {0, 0, 0, 0, 0, 0, 0, 0, 0};
        jPanelLoginLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanelLogin.setLayout(jPanelLoginLayout);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Benvingut/da al sistema de gestió BiblioEdu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 0, 0);
        jPanelLogin.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 131;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanelLogin.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 14, 0, 0);
        jPanelLogin.add(jSeparator2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Per continuar, si us plau, introdueixi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipadx = 110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 70, 0, 10);
        jPanelLogin.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Contrassenya:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(9, 10, 0, 0);
        jPanelLogin.add(jLabel4, gridBagConstraints);

        jTextFieldUsuari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldUsuari.setText("userTest");
        jTextFieldUsuari.setToolTipText("Usuari");
        jTextFieldUsuari.setBorder(null);
        jTextFieldUsuari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuariKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanelLogin.add(jTextFieldUsuari, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Usuari:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 60, 0, 0);
        jPanelLogin.add(jLabel5, gridBagConstraints);

        ButtonIniciarSessio.setBackground(new java.awt.Color(0, 102, 102));
        ButtonIniciarSessio.setForeground(new java.awt.Color(153, 255, 255));
        ButtonIniciarSessio.setText("Iniciar sessió");
        ButtonIniciarSessio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIniciarSessioActionPerformed(evt);
            }
        });
        ButtonIniciarSessio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtonIniciarSessioKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 80, 0);
        jPanelLogin.add(ButtonIniciarSessio, gridBagConstraints);

        jPasswordField1.setText("userTest");
        jPasswordField1.setBorder(null);
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        jPanelLogin.add(jPasswordField1, gridBagConstraints);

        jPanelMenus.add(jPanelLogin, "cardLogin");

        jPanelPrincipal.setVisible(false);
        jPanelPrincipal.setBackground(new java.awt.Color(204, 255, 255));
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(410, 295));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(410, 295));
        jPanelPrincipal.setLayout(new java.awt.GridBagLayout());

        jLabelTitolRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTitolRol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelTitolRol.setText("Rol actual: ");
        jLabelTitolRol.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabelTitolRol.setMinimumSize(new java.awt.Dimension(0, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 220;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 180, 0, 0);
        jPanelPrincipal.add(jLabelTitolRol, gridBagConstraints);

        jLabelTitolMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTitolMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelTitolMenu.setText("Menú principal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 319;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanelPrincipal.add(jLabelTitolMenu, gridBagConstraints);

        jPanelContenedorMenus.setBackground(new java.awt.Color(204, 255, 255));
        jPanelContenedorMenus.setLayout(new java.awt.CardLayout());

        perfilUsuariPanel = new PerfilUsuari();
        jPanelContenedorMenus.add(perfilUsuariPanel, "perfilUsuariPanel");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 410;
        gridBagConstraints.ipady = 350;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        jPanelPrincipal.add(jPanelContenedorMenus, gridBagConstraints);

        jPanelMenus.add(jPanelPrincipal, "cardPrincipal");

        jPanel1.add(jPanelMenus, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIniciarSessioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIniciarSessioActionPerformed

        boolean loginCorrecte = false;

        usuari = jTextFieldUsuari.getText();
        contrassenya = obtenirContrassenya();

        //comprovem que s'hagi introduit usuari i contrassenya i iniciem la connexió
        boolean userPassIntroduits = comprovacio(usuari, contrassenya);

        System.out.println(usuari + " " + contrassenya);

        if (userPassIntroduits) {

            connexio = new Connection(usuari, contrassenya, jPanel1);
            loginCorrecte = connexio.iniciarSessio();
        }

        if (loginCorrecte) {
            rol = connexio.getRol();
            codi = connexio.getCodi();

            jPanelLogin.setVisible(false);

            System.out.println(codi);
            System.out.println(rol);

            mostrarMenuPrincipal();
        }
    }//GEN-LAST:event_ButtonIniciarSessioActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ButtonIniciarSessio.doClick();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jTextFieldUsuariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ButtonIniciarSessio.doClick();
        }
    }//GEN-LAST:event_jTextFieldUsuariKeyPressed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int logout = JOptionPane.showConfirmDialog(jPanel1, "Desitja tancar la sessió actual?", "Tancar sessió", JOptionPane.OK_CANCEL_OPTION);
        if (logout == 0) {
            connexio.logOut();
            usuari = "";
            contrassenya = "";
            jButtonLogout.setVisible(false);
            jPanelPrincipal.setVisible(false);
            jPanelLogin.setVisible(true);
            jPasswordField1.setText("");
            jPanel2ContenedorBotones.setVisible(false);
            jPanelBibliotecari.setVisible(false);
            jPanelAdmin.setVisible(false);
            perfilUsuariPanel.setVisible(false);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void ButtonIniciarSessioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonIniciarSessioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ButtonIniciarSessio.doClick();
        }
    }//GEN-LAST:event_ButtonIniciarSessioKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        
        jPanelContenedorMenus.setVisible(true);
        perfilUsuariPanel.setIdTextField(usuari);
        
//        Container contenedor = jPanelContenedorMenus.getParent();
//        Dimension dimensionContenedor = contenedor.getSize();
//        perfilUsuariPanel.setPreferredSize(dimensionContenedor);
//        
//        CardLayout cl = (CardLayout)jPanelContenedorMenus.getLayout();
//        cl.show(jPanelContenedorMenus, "perfilUsuariPanel");
    }//GEN-LAST:event_jButtonPerfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIniciarSessio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelBenvinguda;
    private javax.swing.JLabel jLabelTitolMenu;
    private javax.swing.JLabel jLabelTitolRol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2ContenedorBotones;
    private javax.swing.JPanel jPanelAdmin;
    private javax.swing.JPanel jPanelAdmin1;
    private javax.swing.JPanel jPanelBibliotecari;
    private javax.swing.JPanel jPanelBibliotecari1;
    private javax.swing.JPanel jPanelContenedorMenus;
    private javax.swing.JPanel jPanelLateral;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMenus;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPanel jPanelUsuario1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldUsuari;
    // End of variables declaration//GEN-END:variables

    private boolean comprovacio(String user, String pass) {
        boolean ok = false;

        if (user.length() < 1) {
            ok = false;
            JOptionPane.showMessageDialog(jPanel1, "Si us plau, introdueixi un usuari.");

        } else if (pass.length() < 1) {
            ok = false;
            JOptionPane.showMessageDialog(jPanel1, "Si us plau, introdueixi una contrassenya.");

        } else {
            ok = true;
        }

        return ok;
    }

    private String obtenirContrassenya() {

        char[] contrassenyaChar = jPasswordField1.getPassword();
        StringBuilder contrassenyaSB = new StringBuilder();
        for (char c : contrassenyaChar) {
            contrassenyaSB.append(c);
        }
        contrassenya = contrassenyaSB.toString();

        return contrassenya;
    }

    private void mostrarMenuPrincipal() {
        jPanelLogin.setVisible(false);
        jButtonLogout.setVisible(true);

        jPanelPrincipal.setVisible(true);
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
        
        jPanelContenedorMenus.setVisible(false);

        jLabelTitolRol.setText("Rol actual: " + rol);
        jLabelBenvinguda.setText(jLabelBenvinguda + usuari);
        
        jLabelBenvinguda.setText("  Benvingut/da, " + usuari);
        jPanelUsuario.setVisible(true);
        
        jPanel2ContenedorBotones.setVisible(true);
        if(rol.equals("bibliotecari") || rol.equals("bibliotecaria")){
            jPanelBibliotecari.setVisible(true);
        }
        if(rol.equals("admin")){
            jPanelBibliotecari.setVisible(true);
            jPanelAdmin.setVisible(true);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);

            }
        });
    }
}
