/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import clientescriptori.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import objectes.Usuari;

/**
 *
 * @author Gonzalo
 */
public class PerfilUsuari extends javax.swing.JPanel {

    private Usuari usuari;
    private Connection connexio;
    /**
     * Creates new form PerfilUsuari
     */
    public PerfilUsuari() {
        initComponents();
    }

    public void setUsuari(Usuari user) {
        this.usuari = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomUsuari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordFieldNova = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldNovaConf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFielCognoms = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFielIdDataNaixement = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFielIdEmail = new javax.swing.JTextField();
        jButtonDesferCanvis = new javax.swing.JButton();
        jButtonGuardarCanvis = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Id d'usuari:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));
        add(jTextFieldNomUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, -1));

        jLabel2.setText("Contrassenya:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jPasswordField1.setEditable(false);
        jPasswordField1.setText("jPasswordField1");
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 145, -1));

        jPasswordFieldNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldNovaActionPerformed(evt);
            }
        });
        add(jPasswordFieldNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, -1));

        jLabel3.setText("Nova contrassenya:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        add(jPasswordFieldNovaConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, -1));

        jLabel4.setText("Confirmar:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel5.setText("Nom:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextFieldId.setEditable(false);
        add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        jTextFielCognoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielCognomsActionPerformed(evt);
            }
        });
        add(jTextFielCognoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 230, -1));

        jLabel6.setText("Cognoms:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setText("Data naixement:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jTextFielIdDataNaixement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdDataNaixementActionPerformed(evt);
            }
        });
        add(jTextFielIdDataNaixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 200, -1));

        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jTextFielIdEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdEmailActionPerformed(evt);
            }
        });
        add(jTextFielIdEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 250, -1));

        jButtonDesferCanvis.setText("Desfer canvis");
        add(jButtonDesferCanvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jButtonGuardarCanvis.setText("Guardar canvis");
        jButtonGuardarCanvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCanvisActionPerformed(evt);
            }
        });
        add(jButtonGuardarCanvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("El meu perfil:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void jTextFielIdUsuari1ActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void jTextFielCognomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielCognomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielCognomsActionPerformed

    private void jTextFielIdDataNaixementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdDataNaixementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdDataNaixementActionPerformed

    private void jTextFielIdEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdEmailActionPerformed

    private void jPasswordFieldNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldNovaActionPerformed

    private void jButtonGuardarCanvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCanvisActionPerformed

        String newPass = obtenirContrassenya(jPasswordFieldNova);
        String newPassConf = obtenirContrassenya(jPasswordFieldNovaConf);
        if (newPass.equals(newPassConf)) {
            usuari.setPass(newPass);
            usuari.setNom(jTextFieldNomUsuari.getText());
            String cognoms = jTextFielCognoms.getText();
            String[] arrayCognoms = cognoms.split(" ");
            if (arrayCognoms.length > 0) {
                usuari.setPrimerCognom(arrayCognoms[0]);
            }
            if (arrayCognoms.length > 1) {
                usuari.setSegonCognom(arrayCognoms[1]);
            }
            try {
                usuari.setDataNaixement(convertirDataString(jTextFielIdDataNaixement.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
            }
            usuari.setEmail(jTextFielIdEmail.getText());
            
            JOptionPane.showMessageDialog(jCheckBox1, "Informació actualitzada amb éxit");
            System.out.println("Informació no actualitzada, falta petició al servidor per canviar informació personal (només poden admins i bibliotecaris)");
            
        } else {
            JOptionPane.showMessageDialog(jCheckBox1, "La nova contrassenya introduïda no és correcta.", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtonGuardarCanvisActionPerformed

    public void setIdTextField(String id) {
        jTextFieldId.setText(id);
    }

    public void setjTextFieldNomUsuari(String nom) {
        jTextFieldNomUsuari.setText(nom);
    }

    public void setjTextFielCognoms(String cognoms) {
        jTextFielCognoms.setText(cognoms);
    }

    public void setjTextFielIdDataNaixement(Date data) {
        jTextFielIdDataNaixement.setText(data.toString());
    }

    public void setjTextFielIdEmail(String email) {
        jTextFielIdEmail.setText(email);
    }

    public void setjTextFieldId(JTextField jTextFieldId) {
        this.jTextFieldId = jTextFieldId;
    }

    public void jTextFieldIdUsuariActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private String obtenirContrassenya(JPasswordField jpf) {

        char[] contrassenyaChar = jpf.getPassword();
        StringBuilder contrassenyaSB = new StringBuilder();
        for (char c : contrassenyaChar) {
            contrassenyaSB.append(c);
        }
        String contrassenya = contrassenyaSB.toString();

        return contrassenya;
    }

    public static Date convertirDataString(String data) throws ParseException {
        Date r;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date dataConvertida = null;

        if (data == null) {
            r = null;
        } else {
            r = dateFormat.parse(data);
        }

        return r;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesferCanvis;
    private javax.swing.JButton jButtonGuardarCanvis;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldNova;
    private javax.swing.JPasswordField jPasswordFieldNovaConf;
    private javax.swing.JTextField jTextFielCognoms;
    private javax.swing.JTextField jTextFielIdDataNaixement;
    private javax.swing.JTextField jTextFielIdEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNomUsuari;
    // End of variables declaration//GEN-END:variables

    public void setConnection(Connection connexio) {
        this.connexio = connexio;
    }
}
