/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import clientescriptori.Connection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import objectes.Usuari;
import utils.Utils;

/**
 *
 * @author Gonzalo
 */
public class PerfilUsuari extends javax.swing.JPanel {

    private Usuari usuari;
    private Connection connexio;
    private ImageIcon fotoPerfilIcon;
    private Image fotoPerfil;

    /**
     * Creates new form PerfilUsuari
     */
    public PerfilUsuari() {
        initComponents();
    }

    public void setUsuari(Usuari user) throws IOException {
        this.usuari = user;
        System.out.println("cargando imagen del usuario...");
        try {

            ByteArrayInputStream inputStream = new ByteArrayInputStream(usuari.getImageData());

            // Crear objecte Image a partir del InputStream
            Image imagen = ImageIO.read(inputStream);
            ImageIcon imageIcon = new ImageIcon(imagen);
            setImageIcon(escalarImagen(jPanelImagen, imageIcon));
            
        } catch (Exception e) {
            System.out.println("error: " + e);
            System.out.println(usuari.getImageData());
        }
//        if (usuari.getImageData() != null) {
//            try {
//                setImageIcon(Utils.convertirBytesAImagen(usuari.getImageData()));
//            } catch (Exception e) {
//                System.out.println("error: " + e + " imposible cargar foto perfil");
//            }
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomUsuari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFielCognoms = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFielIdDataNaixement = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFielIdEmail = new javax.swing.JTextField();
        jButtonDesferCanvis = new javax.swing.JButton();
        jButtonGuardarCanvis = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonActualitzaContrassenya = new javax.swing.JButton();
        jPanelImagen = new javax.swing.JPanel();
        jLabelFotoPerfil = new javax.swing.JLabel();
        jButtonEditarImatge = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("ID d'usuari:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        add(jTextFieldNomUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 250, -1));

        jLabel5.setText("Nom:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jTextFieldId.setEditable(false);
        add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, -1));

        jTextFielCognoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielCognomsActionPerformed(evt);
            }
        });
        add(jTextFielCognoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 230, -1));

        jLabel6.setText("Cognoms:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel7.setText("Data naixement:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jTextFielIdDataNaixement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdDataNaixementActionPerformed(evt);
            }
        });
        add(jTextFielIdDataNaixement, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 200, -1));

        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jTextFielIdEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdEmailActionPerformed(evt);
            }
        });
        add(jTextFielIdEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 250, -1));

        jButtonDesferCanvis.setText("Desfer canvis");
        jButtonDesferCanvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesferCanvisActionPerformed(evt);
            }
        });
        add(jButtonDesferCanvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jButtonGuardarCanvis.setText("Guardar canvis");
        jButtonGuardarCanvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCanvisActionPerformed(evt);
            }
        });
        add(jButtonGuardarCanvis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel9.setText("El meu perfil:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonActualitzaContrassenya.setText("Canviar contrassenya");
        jButtonActualitzaContrassenya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualitzaContrassenyaActionPerformed(evt);
            }
        });
        add(jButtonActualitzaContrassenya, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 160, -1));

        jPanelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/default_user.jpg"))); // NOI18N
        jLabelFotoPerfil.setToolTipText("");
        jPanelImagen.add(jLabelFotoPerfil);

        add(jPanelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 120, 120));

        jButtonEditarImatge.setText("Editar imatge");
        jButtonEditarImatge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarImatgeActionPerformed(evt);
            }
        });
        add(jButtonEditarImatge, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void jTextFielIdUsuari1ActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void jTextFielCognomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielCognomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielCognomsActionPerformed

    private void jTextFielIdDataNaixementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdDataNaixementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdDataNaixementActionPerformed

    private void jTextFielIdEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdEmailActionPerformed

    private void jButtonGuardarCanvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCanvisActionPerformed

        usuari.setNom(jTextFieldNomUsuari.getText());
        String cognoms = jTextFielCognoms.getText();
        String[] arrayCognoms = cognoms.split(" ");

        if (arrayCognoms.length > 0) {
            usuari.setPrimerCognom(arrayCognoms[0]);
        }
        if (arrayCognoms.length > 1) {
            usuari.setSegonCognom(arrayCognoms[1]);
        }
        try {
            usuari.setDataNaixement(convertirDataString(jTextFielIdDataNaixement.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
        }
        usuari.setEmail(jTextFielIdEmail.getText());
        System.out.println(usuari.toString());
        JOptionPane.showMessageDialog(jCheckBox1, "Informació actualitzada amb éxit");
        //System.out.println("Informació no actualitzada, falta petició al servidor per canviar informació personal (només poden admins i bibliotecaris)");
        Connection.modificarUsuari(usuari);
    }//GEN-LAST:event_jButtonGuardarCanvisActionPerformed

    private void jButtonActualitzaContrassenyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualitzaContrassenyaActionPerformed

        CanviaPass canviaPass = new CanviaPass();
        canviaPass.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        canviaPass.setVisible(true);


    }//GEN-LAST:event_jButtonActualitzaContrassenyaActionPerformed

    //botó que desfà els canvis sense guardar fets a les dades de l'usuari
    private void jButtonDesferCanvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesferCanvisActionPerformed
        jTextFieldNomUsuari.setText(usuari.getNom());
        jTextFielCognoms.setText(usuari.getPrimerCognom() + " " + usuari.getSegonCognom());
        if (usuari.getDataNaixement() != null) {
            jTextFielIdDataNaixement.setText(usuari.getDataNaixement().toString());
        } else {
            jTextFielIdDataNaixement.setText(null); //falta implementar calendari per seleccionar data
        }
        jTextFielIdEmail.setText(usuari.getEmail());
    }//GEN-LAST:event_jButtonDesferCanvisActionPerformed

    private void jButtonEditarImatgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarImatgeActionPerformed
        //obrim el menu per buscar arxius:
        JFileChooser selectorArxius = new JFileChooser();
        selectorArxius.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen",
                "jpg", "jpeg", "png", "gif");
        selectorArxius.addChoosableFileFilter(filtro);
        selectorArxius.setFileFilter(filtro);

        int result = selectorArxius.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File imatge = selectorArxius.getSelectedFile();
            fotoPerfilIcon = new ImageIcon(imatge.getPath());
            try {
                fotoPerfil = ImageIO.read(imatge);
            } catch (IOException ex) {
                Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
            }

            jLabelFotoPerfil.setIcon(escalarImagen(jPanelImagen, fotoPerfilIcon));
            BufferedImage bi = new BufferedImage(fotoPerfilIcon.getIconWidth(), fotoPerfilIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
            fotoPerfilIcon.paintIcon(null, bi.getGraphics(), 0, 0);
            try {
                byte[] fotoPerfilBytes = Utils.convertirImagenABytes(bi);
                usuari.setImageData(fotoPerfilBytes);
                Connection.modificarUsuari(usuari);
            } catch (IOException ex) {
                Logger.getLogger(PerfilUsuari.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButtonEditarImatgeActionPerformed

    public void setIdTextField(String id) {
        jTextFieldId.setText(id);
    }

    public void setjTextFieldNomUsuari(String nom) {
        jTextFieldNomUsuari.setText(nom);
    }

    public void setjTextFielCognoms(String cognoms) {
        jTextFielCognoms.setText(cognoms);
    }

    public void setjTextFielIdDataNaixement(Date data) {
        jTextFielIdDataNaixement.setText(data.toString());
    }

    public void setjTextFielIdEmail(String email) {
        jTextFielIdEmail.setText(email);
    }

    public void setjTextFieldId(JTextField jTextFieldId) {
        this.jTextFieldId = jTextFieldId;
    }

    public void jTextFieldIdUsuariActionPerformed(java.awt.event.ActionEvent evt) {

    }

    public static Date convertirDataString(String data) throws ParseException {
        Date r;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date dataConvertida = null;

        if (data == null || data.equals("")) {
            r = null;
        } else {
            r = dateFormat.parse(data);
        }

        return r;
    }

    public ImageIcon escalarImagen(JPanel panel, ImageIcon imageIcon) {
        //Obtenim el tamany del panell
        int panelWidth = panel.getWidth();
        int panelHeight = panel.getHeight();

        //Obtenim el tamany de l'imageIcon
        int imageWidth = imageIcon.getIconWidth();
        int imageHeight = imageIcon.getIconHeight();

        //calculem l'escala necessària per que l'imatge s'ajusti
        double escala = Math.min((double) panelWidth / imageWidth, (double) panelHeight / imageHeight);
        Image imatgeEscalada = imageIcon.getImage().getScaledInstance((int) (imageWidth * escala),
                (int) (imageHeight * escala), Image.SCALE_SMOOTH);

        ImageIcon imageIconEscalat = new ImageIcon(imatgeEscalada);

        return imageIconEscalat;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualitzaContrassenya;
    private javax.swing.JButton jButtonDesferCanvis;
    private javax.swing.JButton jButtonEditarImatge;
    private javax.swing.JButton jButtonGuardarCanvis;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFotoPerfil;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JTextField jTextFielCognoms;
    private javax.swing.JTextField jTextFielIdDataNaixement;
    private javax.swing.JTextField jTextFielIdEmail;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNomUsuari;
    // End of variables declaration//GEN-END:variables

    public void setImageIcon(ImageIcon imageIcon) {

        this.fotoPerfilIcon = imageIcon;
        jLabelFotoPerfil.setIcon(escalarImagen(jPanelImagen, fotoPerfilIcon));
        BufferedImage bi = new BufferedImage(fotoPerfilIcon.getIconWidth(), fotoPerfilIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
        fotoPerfilIcon.paintIcon(null, bi.getGraphics(), 0, 0);
    }

    public void setConnection(Connection connexio) {
        this.connexio = connexio;
    }
}
