/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Gonzalo
 */
public class PerfilUsuari extends javax.swing.JPanel {

    /**
     * Creates new form PerfilUsuari
     */
    public PerfilUsuari() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomUsuari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordFieldNova = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldNovaConf = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdUsuari = new javax.swing.JTextField();
        jTextFielIdUsuari2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFielIdUsuari3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFielIdUsuari4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(204, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(600, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Id d'usuari:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jTextFieldNomUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        add(jTextFieldNomUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 150, -1));

        jLabel2.setText("Contrassenya:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jPasswordField1.setEditable(false);
        jPasswordField1.setText("jPasswordField1");
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 145, -1));

        jPasswordFieldNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldNovaActionPerformed(evt);
            }
        });
        add(jPasswordFieldNova, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, -1));

        jLabel3.setText("Nova contrassenya:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        add(jPasswordFieldNovaConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 140, -1));

        jLabel4.setText("Confirmar:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel5.setText("Nom:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextFieldIdUsuari.setEditable(false);
        jTextFieldNomUsuari.setText(LoginScreen.usuari);
        jTextFieldIdUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdUsuariActionPerformed(evt);
            }
        });
        add(jTextFieldIdUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        jTextFieldNomUsuari.setText(LoginScreen.usuari);
        jTextFielIdUsuari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdUsuari2ActionPerformed(evt);
            }
        });
        add(jTextFielIdUsuari2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, -1));

        jLabel6.setText("Cognoms:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setText("Data naixement:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jTextFieldNomUsuari.setText(LoginScreen.usuari);
        jTextFielIdUsuari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdUsuari3ActionPerformed(evt);
            }
        });
        add(jTextFielIdUsuari3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, -1));

        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTextFieldNomUsuari.setText(LoginScreen.usuari);
        jTextFielIdUsuari4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielIdUsuari4ActionPerformed(evt);
            }
        });
        add(jTextFielIdUsuari4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 150, -1));

        jButton1.setText("Desfer canvis");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jButton2.setText("Guardar canvis");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none
    private void jTextFielIdUsuari1ActionPerformed(java.awt.event.ActionEvent evt) {

    }
    private void jTextFielIdUsuari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdUsuari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdUsuari2ActionPerformed

    private void jTextFielIdUsuari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdUsuari3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdUsuari3ActionPerformed

    private void jTextFielIdUsuari4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielIdUsuari4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielIdUsuari4ActionPerformed

    private void jPasswordFieldNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldNovaActionPerformed

    public void setIdTextField(String id) {
        jTextFieldIdUsuari.setText(id);
    }

    public void jTextFieldIdUsuariActionPerformed(java.awt.event.ActionEvent evt) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldNova;
    private javax.swing.JPasswordField jPasswordFieldNovaConf;
    private javax.swing.JTextField jTextFielIdUsuari2;
    private javax.swing.JTextField jTextFielIdUsuari3;
    private javax.swing.JTextField jTextFielIdUsuari4;
    private javax.swing.JTextField jTextFieldIdUsuari;
    private javax.swing.JTextField jTextFieldNomUsuari;
    // End of variables declaration//GEN-END:variables
}
